# Generated by Django 5.2.1 on 2025-06-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_educationbackground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationbackground',
            name='course',
        ),
        migrations.RemoveField(
            model_name='educationbackground',
            name='school_name',
        ),
        migrations.AddField(
            model_name='educationbackground',
            name='general_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='educationbackground',
            name='highschool_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationbackground',
            name='strand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='educationbackground',
            name='school_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationbackground',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_backgrounds', to='student.student'),
        ),
    ]
