# Generated by Django 5.2.1 on 2025-06-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_educationbackground_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
