# Generated by Django 5.2.1 on 2025-06-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_date_of_birth_student_birth_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='national_id',
            new_name='nationality',
        ),
    ]
