# Generated by Django 5.2.1 on 2025-06-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
