# Generated by Django 5.2.1 on 2025-06-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_attended', models.CharField(max_length=50)),
                ('degree_earned', models.CharField(max_length=50)),
                ('year_graduated', models.CharField(max_length=50)),
                ('latin_honors', models.CharField(blank=True, max_length=50, null=True)),
                ('thesis_title', models.CharField(blank=True, max_length=100, null=True)),
                ('school_address', models.TextField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='student.student')),
            ],
        ),
    ]
