# Generated by Django 5.2.1 on 2025-06-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_college_course_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.IntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_number',
            field=models.IntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
