# Generated by Django 5.2.1 on 2025-06-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_number',
            field=models.IntegerField(),
        ),
    ]
