# Generated by Django 5.2.1 on 2025-06-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollmentStatus',
            new_name='EnrollmentStatu',
        ),
    ]
