# Generated by Django 5.2.1 on 2025-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_enrollment_course_requireddocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requireddocument',
            old_name='enrollment',
            new_name='enrollment_id',
        ),
        migrations.RenameField(
            model_name='requireddocument',
            old_name='is_submitted',
            new_name='good_moral',
        ),
        migrations.RemoveField(
            model_name='requireddocument',
            name='document_name',
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='medical_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='psa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='tor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='transfer_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='vaccination_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='valid_id',
            field=models.BooleanField(default=False),
        ),
    ]
